### ISSUE TITLE
(Hopefully) Fix File Conflict

### ISSUE THREAD

**Issue by robcore** [friedrich420/S4-AEL-Kernel-Lollipop#1]
Hi Friedrich,
I know that bugs are usually repaired via pull-requests, but please bear with me as I'm slowly learning how to use git without breaking the internet...

In this case, the cherry-pick conflict existed within the file itself, meaning the issue could very well have been limited to something trivial such as line-numbers, etc.
" Decrease time to enter sleep [Pafcholini] "
Fix in question involves original commit a69aabc058de3b728f57a93d8cd7c0a2323d39fc and its revert 056343699e5b70191c782e7757869b3275ed8b80, file is  kernel/power/process.c.

+<<<<<<< HEAD
 #define TIMEOUT    (20 \* HZ)
+=======
+unsigned int __read_mostly freeze_timeout_msecs = 2 \* MSEC_PER_SEC;
+>>>>>>> 42a031f... Decrease time to enter sleep [Pafcholini]

as you can see, only two lines should have been added:
 #define TIMEOUT    (20 \* HZ)

+unsigned int __read_mostly freeze_timeout_msecs = 2 \* MSEC_PER_SEC;

As a current user of this kernel, i can attest that time to enter sleep is almost instantaneous as it is, so I don't know if this is something you think even needs to be tested.  However I figured I'd point it out if you thought it might be worth trying/compatible.  Take care and sorry I will learn how to do pull requests soon without screwing up my own main project (git's hard, man). -Rob

**Comment by friedrich420** [comment]
Thank you so much!

**Comment by robcore** [comment]
No problem!  Though I messed up, looks like only one line is added:

+unsigned int __read_mostly freeze_timeout_msecs = 2 \* MSEC_PER_SEC;

But I'm sure you already noticed that...Anyway, thank YOU for all of the awesome contributing you do, I'm just doing my best to learn so I can help one day : P
